/**
 * Preset Palettes for HSV Palette Generator
 *
 * These are built-in color palettes that demonstrate various use cases
 * and provide starting points for users.
 */

import type { PaletteData } from "@/lib/supabase";
import { PRESET_MUI_COMPLETE } from "./muiComplete";

// ============================================================================
// PRESET PALETTE DEFINITIONS
// ============================================================================

export const PRESET_MATERIAL_UI: PaletteData = [
  {
    id: "mui-blue",
    name: "Blue",
    muiName: "blue",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#E3F2FD",
        locked: true,
        hsv: { h: 207, s: 11, v: 99 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#BBDEFB",
        locked: false,
        hsv: { h: 207, s: 26, v: 98 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#90CAF9",
        locked: false,
        hsv: { h: 207, s: 42, v: 98 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#64B5F6",
        locked: false,
        hsv: { h: 207, s: 59, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#42A5F5",
        locked: false,
        hsv: { h: 207, s: 73, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#2196F3",
        locked: true,
        hsv: { h: 207, s: 86, v: 95 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#1E88E5",
        locked: false,
        hsv: { h: 207, s: 87, v: 90 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#1976D2",
        locked: false,
        hsv: { h: 210, s: 88, v: 82 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#1565C0",
        locked: false,
        hsv: { h: 210, s: 89, v: 75 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#0D47A1",
        locked: true,
        hsv: { h: 210, s: 92, v: 63 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
];

export const PRESET_SAGE_GREEN: PaletteData = [
  {
    id: "sage-green",
    name: "Sage Green",
    muiName: "primary",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#F5FAFA",
        locked: false,
        hsv: { h: 180, s: 3, v: 98 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#DFEEF0",
        locked: false,
        hsv: { h: 187, s: 7, v: 94 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#C3DFE2",
        locked: false,
        hsv: { h: 186, s: 13, v: 89 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#A6CED1",
        locked: false,
        hsv: { h: 184, s: 20, v: 82 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#87B9BE",
        locked: false,
        hsv: { h: 185, s: 29, v: 75 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#68A3A8",
        locked: true,
        hsv: { h: 185, s: 38, v: 66 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#45848A",
        locked: false,
        hsv: { h: 185, s: 50, v: 54 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#245E64",
        locked: false,
        hsv: { h: 186, s: 63, v: 39 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#0D383D",
        locked: false,
        hsv: { h: 186, s: 75, v: 24 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#02181A",
        locked: false,
        hsv: { h: 187, s: 88, v: 10 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
];

export const PRESET_SUNSET_ORANGE: PaletteData = [
  {
    id: "sunset-orange",
    name: "Sunset Orange",
    muiName: "orange",
    extrapolationMode: "expressive",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#FFF3E0",
        locked: false,
        hsv: { h: 33, s: 12, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#FFE0B2",
        locked: false,
        hsv: { h: 33, s: 30, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#FFCC80",
        locked: false,
        hsv: { h: 33, s: 50, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#FFB74D",
        locked: false,
        hsv: { h: 33, s: 70, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#FFA726",
        locked: false,
        hsv: { h: 33, s: 85, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#FF9800",
        locked: true,
        hsv: { h: 36, s: 100, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#FB8C00",
        locked: false,
        hsv: { h: 33, s: 100, v: 98 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#F57C00",
        locked: false,
        hsv: { h: 31, s: 100, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#EF6C00",
        locked: false,
        hsv: { h: 27, s: 100, v: 94 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#E65100",
        locked: false,
        hsv: { h: 21, s: 100, v: 90 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
];

export const PRESET_PURPLE_RAIN: PaletteData = [
  {
    id: "purple-rain",
    name: "Purple Rain",
    muiName: "purple",
    extrapolationMode: "functional-saturated",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#F3E5F5",
        locked: false,
        hsv: { h: 291, s: 7, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#E1BEE7",
        locked: false,
        hsv: { h: 291, s: 18, v: 91 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#CE93D8",
        locked: false,
        hsv: { h: 291, s: 32, v: 85 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#BA68C8",
        locked: false,
        hsv: { h: 291, s: 48, v: 78 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#AB47BC",
        locked: false,
        hsv: { h: 291, s: 62, v: 74 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#9C27B0",
        locked: true,
        hsv: { h: 291, s: 77, v: 69 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#8E24AA",
        locked: false,
        hsv: { h: 291, s: 79, v: 67 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#7B1FA2",
        locked: false,
        hsv: { h: 291, s: 81, v: 64 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#6A1B9A",
        locked: false,
        hsv: { h: 291, s: 82, v: 60 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#4A148C",
        locked: false,
        hsv: { h: 291, s: 86, v: 55 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
];

export const PRESET_FOREST_GREEN: PaletteData = [
  {
    id: "forest-green",
    name: "Forest Green",
    muiName: "green",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#E8F5E9",
        locked: false,
        hsv: { h: 122, s: 7, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#C8E6C9",
        locked: false,
        hsv: { h: 122, s: 14, v: 90 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#A5D6A7",
        locked: false,
        hsv: { h: 123, s: 23, v: 84 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#81C784",
        locked: false,
        hsv: { h: 123, s: 35, v: 78 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#66BB6A",
        locked: false,
        hsv: { h: 123, s: 45, v: 73 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#4CAF50",
        locked: true,
        hsv: { h: 122, s: 56, v: 69 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#43A047",
        locked: false,
        hsv: { h: 122, s: 58, v: 63 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#388E3C",
        locked: false,
        hsv: { h: 122, s: 61, v: 56 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#2E7D32",
        locked: false,
        hsv: { h: 122, s: 63, v: 49 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#1B5E20",
        locked: false,
        hsv: { h: 123, s: 72, v: 37 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
];

// ============================================================================
// PRESET REGISTRY
// ============================================================================

export interface PresetPaletteInfo {
  id: string;
  name: string;
  description: string;
  category: "material" | "nature" | "vibrant" | "neutral" | "custom";
  tags: string[];
  data: PaletteData;
}

export const PRESET_PALETTES: PresetPaletteInfo[] = [
  {
    id: "mui-complete",
    name: "Material-UI Complete",
    description:
      "Complete Material-UI v7.3.7 color palette with all 19 official color hues",
    category: "material",
    tags: ["mui", "material-ui", "complete", "official"],
    data: PRESET_MUI_COMPLETE,
  },
  {
    id: "material-ui-blue",
    name: "Material Blue",
    description: "Standard Material-UI blue palette",
    category: "material",
    tags: ["blue", "material", "ui", "standard"],
    data: PRESET_MATERIAL_UI,
  },
  {
    id: "sage-green",
    name: "Sage Green",
    description: "Calming sage green palette perfect for nature-themed designs",
    category: "nature",
    tags: ["green", "sage", "calm", "nature"],
    data: PRESET_SAGE_GREEN,
  },
  {
    id: "sunset-orange",
    name: "Sunset Orange",
    description:
      "Vibrant sunset orange with expressive mode (maintains saturation)",
    category: "vibrant",
    tags: ["orange", "sunset", "vibrant", "warm"],
    data: PRESET_SUNSET_ORANGE,
  },
  {
    id: "purple-rain",
    name: "Purple Rain",
    description: "Rich purple with saturated darks (functional-saturated mode)",
    category: "vibrant",
    tags: ["purple", "rich", "saturated"],
    data: PRESET_PURPLE_RAIN,
  },
  {
    id: "forest-green",
    name: "Forest Green",
    description: "Natural forest green palette",
    category: "nature",
    tags: ["green", "forest", "nature"],
    data: PRESET_FOREST_GREEN,
  },
];

/**
 * Get a preset palette by ID
 */
export function getPresetById(id: string): PresetPaletteInfo | undefined {
  return PRESET_PALETTES.find((preset) => preset.id === id);
}

/**
 * Get presets by category
 */
export function getPresetsByCategory(
  category: PresetPaletteInfo["category"]
): PresetPaletteInfo[] {
  return PRESET_PALETTES.filter((preset) => preset.category === category);
}

/**
 * Get presets by tag
 */
export function getPresetsByTag(tag: string): PresetPaletteInfo[] {
  return PRESET_PALETTES.filter((preset) => preset.tags.includes(tag));
}
