/**
 * Complete Material-UI Color Palette (v7.3.7)
 * All 19 official MUI color palettes with 10 shades each (50-900)
 *
 * Includes: Red, Pink, Purple, Deep Purple, Indigo, Blue, Light Blue, Cyan,
 * Teal, Green, Light Green, Lime, Yellow, Amber, Orange, Deep Orange, Brown,
 * Grey, and Blue Grey
 *
 * Source: https://mui.com/material-ui/customization/color/#color-palette
 */

import type { PaletteData } from "@/lib/supabase";

export const PRESET_MUI_COMPLETE: PaletteData = [
  // Red
  {
    id: "mui-red",
    name: "Red",
    muiName: "red",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#ffebee",
        locked: false,
        hsv: { h: 351, s: 8, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#ffcdd2",
        locked: false,
        hsv: { h: 351, s: 20, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#ef9a9a",
        locked: false,
        hsv: { h: 0, s: 36, v: 94 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#e57373",
        locked: false,
        hsv: { h: 0, s: 50, v: 90 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#ef5350",
        locked: false,
        hsv: { h: 1, s: 67, v: 94 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#f44336",
        locked: true,
        hsv: { h: 4, s: 78, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#e53935",
        locked: false,
        hsv: { h: 1, s: 75, v: 90 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#d32f2f",
        locked: false,
        hsv: { h: 0, s: 78, v: 83 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#c62828",
        locked: false,
        hsv: { h: 0, s: 80, v: 78 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#b71c1c",
        locked: false,
        hsv: { h: 0, s: 85, v: 72 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
  // Pink
  {
    id: "mui-pink",
    name: "Pink",
    muiName: "pink",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#fce4ec",
        locked: false,
        hsv: { h: 340, s: 8, v: 99 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#f8bbd0",
        locked: false,
        hsv: { h: 340, s: 25, v: 97 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#f48fb1",
        locked: false,
        hsv: { h: 340, s: 42, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#f06292",
        locked: false,
        hsv: { h: 340, s: 59, v: 94 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#ec407a",
        locked: false,
        hsv: { h: 340, s: 73, v: 93 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#e91e63",
        locked: true,
        hsv: { h: 340, s: 87, v: 91 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#d81b60",
        locked: false,
        hsv: { h: 340, s: 88, v: 85 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#c2185b",
        locked: false,
        hsv: { h: 340, s: 88, v: 76 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#ad1457",
        locked: false,
        hsv: { h: 340, s: 89, v: 68 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#880e4f",
        locked: false,
        hsv: { h: 340, s: 90, v: 53 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
  // Purple
  {
    id: "mui-purple",
    name: "Purple",
    muiName: "purple",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#f3e5f5",
        locked: false,
        hsv: { h: 291, s: 6, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#e1bee7",
        locked: false,
        hsv: { h: 291, s: 17, v: 91 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#ce93d8",
        locked: false,
        hsv: { h: 291, s: 32, v: 85 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#ba68c8",
        locked: false,
        hsv: { h: 291, s: 48, v: 78 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#ab47bc",
        locked: false,
        hsv: { h: 291, s: 62, v: 74 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#9c27b0",
        locked: true,
        hsv: { h: 291, s: 77, v: 69 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#8e24aa",
        locked: false,
        hsv: { h: 291, s: 79, v: 67 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#7b1fa2",
        locked: false,
        hsv: { h: 291, s: 81, v: 64 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#6a1b9a",
        locked: false,
        hsv: { h: 291, s: 83, v: 60 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#4a148c",
        locked: false,
        hsv: { h: 291, s: 86, v: 55 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
  // Deep Purple
  {
    id: "mui-deep-purple",
    name: "Deep Purple",
    muiName: "deepPurple",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#ede7f6",
        locked: false,
        hsv: { h: 260, s: 6, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#d1c4e9",
        locked: false,
        hsv: { h: 260, s: 16, v: 91 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#b39ddb",
        locked: false,
        hsv: { h: 260, s: 28, v: 86 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#9575cd",
        locked: false,
        hsv: { h: 260, s: 43, v: 80 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#7e57c2",
        locked: false,
        hsv: { h: 260, s: 55, v: 76 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#673ab7",
        locked: true,
        hsv: { h: 260, s: 68, v: 72 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#5e35b1",
        locked: false,
        hsv: { h: 260, s: 70, v: 69 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#512da8",
        locked: false,
        hsv: { h: 260, s: 73, v: 66 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#4527a0",
        locked: false,
        hsv: { h: 260, s: 76, v: 63 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#311b92",
        locked: false,
        hsv: { h: 260, s: 81, v: 57 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
  // Indigo
  {
    id: "mui-indigo",
    name: "Indigo",
    muiName: "indigo",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#e8eaf6",
        locked: false,
        hsv: { h: 231, s: 6, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#c5cae9",
        locked: false,
        hsv: { h: 231, s: 16, v: 91 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#9fa8da",
        locked: false,
        hsv: { h: 231, s: 27, v: 85 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#7986cb",
        locked: false,
        hsv: { h: 231, s: 40, v: 80 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#5c6bc0",
        locked: false,
        hsv: { h: 231, s: 52, v: 75 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#3f51b5",
        locked: true,
        hsv: { h: 231, s: 65, v: 71 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#3949ab",
        locked: false,
        hsv: { h: 231, s: 67, v: 67 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#303f9f",
        locked: false,
        hsv: { h: 231, s: 70, v: 62 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#283593",
        locked: false,
        hsv: { h: 231, s: 73, v: 58 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#1a237e",
        locked: false,
        hsv: { h: 231, s: 79, v: 49 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
  // Blue
  {
    id: "mui-blue",
    name: "Blue",
    muiName: "blue",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#e3f2fd",
        locked: false,
        hsv: { h: 207, s: 11, v: 99 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#bbdefb",
        locked: false,
        hsv: { h: 207, s: 26, v: 98 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#90caf9",
        locked: false,
        hsv: { h: 207, s: 42, v: 98 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#64b5f6",
        locked: false,
        hsv: { h: 207, s: 59, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#42a5f5",
        locked: false,
        hsv: { h: 207, s: 73, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#2196f3",
        locked: true,
        hsv: { h: 207, s: 86, v: 95 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#1e88e5",
        locked: false,
        hsv: { h: 207, s: 87, v: 90 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#1976d2",
        locked: false,
        hsv: { h: 210, s: 88, v: 82 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#1565c0",
        locked: false,
        hsv: { h: 210, s: 89, v: 75 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#0d47a1",
        locked: false,
        hsv: { h: 210, s: 92, v: 63 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
  // Light Blue
  {
    id: "mui-light-blue",
    name: "Light Blue",
    muiName: "lightBlue",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#e1f5fe",
        locked: false,
        hsv: { h: 198, s: 11, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#b3e5fc",
        locked: false,
        hsv: { h: 199, s: 29, v: 99 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#81d4fa",
        locked: false,
        hsv: { h: 199, s: 48, v: 98 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#4fc3f7",
        locked: false,
        hsv: { h: 199, s: 68, v: 97 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#29b6f6",
        locked: false,
        hsv: { h: 199, s: 83, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#03a9f4",
        locked: true,
        hsv: { h: 199, s: 99, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#039be5",
        locked: false,
        hsv: { h: 199, s: 99, v: 90 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#0288d1",
        locked: false,
        hsv: { h: 199, s: 99, v: 82 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#0277bd",
        locked: false,
        hsv: { h: 199, s: 99, v: 74 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#01579b",
        locked: false,
        hsv: { h: 205, s: 99, v: 61 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
  // Cyan
  {
    id: "mui-cyan",
    name: "Cyan",
    muiName: "cyan",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#e0f7fa",
        locked: false,
        hsv: { h: 187, s: 10, v: 98 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#b2ebf2",
        locked: false,
        hsv: { h: 187, s: 26, v: 95 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#80deea",
        locked: false,
        hsv: { h: 187, s: 45, v: 92 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#4dd0e1",
        locked: false,
        hsv: { h: 187, s: 66, v: 88 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#26c6da",
        locked: false,
        hsv: { h: 187, s: 82, v: 85 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#00bcd4",
        locked: true,
        hsv: { h: 187, s: 100, v: 83 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#00acc1",
        locked: false,
        hsv: { h: 187, s: 100, v: 76 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#0097a7",
        locked: false,
        hsv: { h: 187, s: 100, v: 65 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#00838f",
        locked: false,
        hsv: { h: 187, s: 100, v: 56 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#006064",
        locked: false,
        hsv: { h: 184, s: 100, v: 39 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
  // Teal
  {
    id: "mui-teal",
    name: "Teal",
    muiName: "teal",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#e0f2f1",
        locked: false,
        hsv: { h: 174, s: 7, v: 95 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#b2dfdb",
        locked: false,
        hsv: { h: 174, s: 20, v: 87 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#80cbc4",
        locked: false,
        hsv: { h: 174, s: 37, v: 80 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#4db6ac",
        locked: false,
        hsv: { h: 174, s: 57, v: 71 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#26a69a",
        locked: false,
        hsv: { h: 174, s: 77, v: 65 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#009688",
        locked: true,
        hsv: { h: 174, s: 100, v: 59 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#00897b",
        locked: false,
        hsv: { h: 174, s: 100, v: 54 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#00796b",
        locked: false,
        hsv: { h: 174, s: 100, v: 47 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#00695c",
        locked: false,
        hsv: { h: 174, s: 100, v: 41 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#004d40",
        locked: false,
        hsv: { h: 174, s: 100, v: 30 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
  // Green
  {
    id: "mui-green",
    name: "Green",
    muiName: "green",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#e8f5e9",
        locked: false,
        hsv: { h: 125, s: 5, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#c8e6c9",
        locked: false,
        hsv: { h: 122, s: 13, v: 90 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#a5d6a7",
        locked: false,
        hsv: { h: 122, s: 23, v: 84 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#81c784",
        locked: false,
        hsv: { h: 123, s: 35, v: 78 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#66bb6a",
        locked: false,
        hsv: { h: 123, s: 45, v: 73 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#4caf50",
        locked: true,
        hsv: { h: 122, s: 57, v: 69 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#43a047",
        locked: false,
        hsv: { h: 123, s: 58, v: 63 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#388e3c",
        locked: false,
        hsv: { h: 123, s: 60, v: 56 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#2e7d32",
        locked: false,
        hsv: { h: 123, s: 63, v: 49 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#1b5e20",
        locked: false,
        hsv: { h: 123, s: 72, v: 37 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
  // Light Green
  {
    id: "mui-light-green",
    name: "Light Green",
    muiName: "lightGreen",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#f1f8e9",
        locked: false,
        hsv: { h: 84, s: 6, v: 97 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#dcedc8",
        locked: false,
        hsv: { h: 88, s: 16, v: 93 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#c5e1a5",
        locked: false,
        hsv: { h: 88, s: 27, v: 88 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#aed581",
        locked: false,
        hsv: { h: 88, s: 39, v: 84 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#9ccc65",
        locked: false,
        hsv: { h: 88, s: 50, v: 80 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#8bc34a",
        locked: true,
        hsv: { h: 88, s: 62, v: 76 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#7cb342",
        locked: false,
        hsv: { h: 88, s: 63, v: 70 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#689f38",
        locked: false,
        hsv: { h: 88, s: 65, v: 62 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#558b2f",
        locked: false,
        hsv: { h: 88, s: 66, v: 55 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#33691e",
        locked: false,
        hsv: { h: 88, s: 71, v: 41 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
  // Lime
  {
    id: "mui-lime",
    name: "Lime",
    muiName: "lime",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#f9fbe7",
        locked: false,
        hsv: { h: 66, s: 8, v: 98 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#f0f4c3",
        locked: false,
        hsv: { h: 66, s: 20, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#e6ee9c",
        locked: false,
        hsv: { h: 66, s: 33, v: 93 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#dce775",
        locked: false,
        hsv: { h: 66, s: 49, v: 91 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#d4e157",
        locked: false,
        hsv: { h: 66, s: 61, v: 88 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#cddc39",
        locked: true,
        hsv: { h: 66, s: 74, v: 86 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#c0ca33",
        locked: false,
        hsv: { h: 66, s: 75, v: 79 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#afb42b",
        locked: false,
        hsv: { h: 64, s: 76, v: 71 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#9e9d24",
        locked: false,
        hsv: { h: 60, s: 77, v: 62 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#827717",
        locked: false,
        hsv: { h: 60, s: 82, v: 51 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
  // Yellow
  {
    id: "mui-yellow",
    name: "Yellow",
    muiName: "yellow",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#fffde7",
        locked: false,
        hsv: { h: 55, s: 10, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#fff9c4",
        locked: false,
        hsv: { h: 54, s: 23, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#fff59d",
        locked: false,
        hsv: { h: 54, s: 38, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#fff176",
        locked: false,
        hsv: { h: 54, s: 54, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#ffee58",
        locked: false,
        hsv: { h: 54, s: 65, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#ffeb3b",
        locked: true,
        hsv: { h: 54, s: 77, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#fdd835",
        locked: false,
        hsv: { h: 51, s: 79, v: 99 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#fbc02d",
        locked: false,
        hsv: { h: 48, s: 82, v: 98 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#f9a825",
        locked: false,
        hsv: { h: 45, s: 85, v: 98 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#f57f17",
        locked: false,
        hsv: { h: 42, s: 91, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
  // Amber
  {
    id: "mui-amber",
    name: "Amber",
    muiName: "amber",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#fff8e1",
        locked: false,
        hsv: { h: 48, s: 12, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#ffecb3",
        locked: false,
        hsv: { h: 45, s: 30, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#ffe082",
        locked: false,
        hsv: { h: 43, s: 49, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#ffd54f",
        locked: false,
        hsv: { h: 42, s: 69, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#ffca28",
        locked: false,
        hsv: { h: 42, s: 84, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#ffc107",
        locked: true,
        hsv: { h: 45, s: 97, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#ffb300",
        locked: false,
        hsv: { h: 42, s: 100, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#ffa000",
        locked: false,
        hsv: { h: 38, s: 100, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#ff8f00",
        locked: false,
        hsv: { h: 34, s: 100, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#ff6f00",
        locked: false,
        hsv: { h: 26, s: 100, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
  // Orange
  {
    id: "mui-orange",
    name: "Orange",
    muiName: "orange",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#fff3e0",
        locked: false,
        hsv: { h: 36, s: 12, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#ffe0b2",
        locked: false,
        hsv: { h: 36, s: 30, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#ffcc80",
        locked: false,
        hsv: { h: 36, s: 50, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#ffb74d",
        locked: false,
        hsv: { h: 36, s: 70, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#ffa726",
        locked: false,
        hsv: { h: 36, s: 85, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#ff9800",
        locked: true,
        hsv: { h: 36, s: 100, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#fb8c00",
        locked: false,
        hsv: { h: 33, s: 100, v: 98 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#f57c00",
        locked: false,
        hsv: { h: 30, s: 100, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#ef6c00",
        locked: false,
        hsv: { h: 27, s: 100, v: 94 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#e65100",
        locked: false,
        hsv: { h: 21, s: 100, v: 90 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
  // Deep Orange
  {
    id: "mui-deep-orange",
    name: "Deep Orange",
    muiName: "deepOrange",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#fbe9e7",
        locked: false,
        hsv: { h: 14, s: 8, v: 98 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#ffccbc",
        locked: false,
        hsv: { h: 14, s: 26, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#ffab91",
        locked: false,
        hsv: { h: 14, s: 43, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#ff8a65",
        locked: false,
        hsv: { h: 14, s: 60, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#ff7043",
        locked: false,
        hsv: { h: 14, s: 74, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#ff5722",
        locked: true,
        hsv: { h: 14, s: 87, v: 100 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#f4511e",
        locked: false,
        hsv: { h: 14, s: 88, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#e64a19",
        locked: false,
        hsv: { h: 14, s: 89, v: 90 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#d84315",
        locked: false,
        hsv: { h: 14, s: 90, v: 85 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#bf360c",
        locked: false,
        hsv: { h: 14, s: 94, v: 75 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
  // Brown
  {
    id: "mui-brown",
    name: "Brown",
    muiName: "brown",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#efebe9",
        locked: false,
        hsv: { h: 20, s: 3, v: 94 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#d7ccc8",
        locked: false,
        hsv: { h: 16, s: 7, v: 84 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#bcaaa4",
        locked: false,
        hsv: { h: 16, s: 13, v: 74 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#a1887f",
        locked: false,
        hsv: { h: 16, s: 21, v: 63 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#8d6e63",
        locked: false,
        hsv: { h: 16, s: 30, v: 55 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#795548",
        locked: true,
        hsv: { h: 16, s: 40, v: 47 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#6d4c41",
        locked: false,
        hsv: { h: 16, s: 40, v: 43 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#5d4037",
        locked: false,
        hsv: { h: 16, s: 41, v: 36 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#4e342e",
        locked: false,
        hsv: { h: 16, s: 41, v: 31 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#3e2723",
        locked: false,
        hsv: { h: 11, s: 42, v: 24 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
  // Grey
  {
    id: "mui-grey",
    name: "Grey",
    muiName: "grey",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#fafafa",
        locked: false,
        hsv: { h: 0, s: 0, v: 98 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#f5f5f5",
        locked: false,
        hsv: { h: 0, s: 0, v: 96 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#eeeeee",
        locked: false,
        hsv: { h: 0, s: 0, v: 93 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#e0e0e0",
        locked: false,
        hsv: { h: 0, s: 0, v: 88 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#bdbdbd",
        locked: false,
        hsv: { h: 0, s: 0, v: 74 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#9e9e9e",
        locked: true,
        hsv: { h: 0, s: 0, v: 62 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#757575",
        locked: false,
        hsv: { h: 0, s: 0, v: 46 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#616161",
        locked: false,
        hsv: { h: 0, s: 0, v: 38 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#424242",
        locked: false,
        hsv: { h: 0, s: 0, v: 26 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#212121",
        locked: false,
        hsv: { h: 0, s: 0, v: 13 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
  // Blue Grey
  {
    id: "mui-blue-grey",
    name: "Blue Grey",
    muiName: "blueGrey",
    extrapolationMode: "functional",
    shadeConfig: [
      { id: "1", label: "50" },
      { id: "2", label: "100" },
      { id: "3", label: "200" },
      { id: "4", label: "300" },
      { id: "5", label: "400" },
      { id: "6", label: "500" },
      { id: "7", label: "600" },
      { id: "8", label: "700" },
      { id: "9", label: "800" },
      { id: "10", label: "900" },
    ],
    shades: [
      {
        id: "shade-1",
        label: "50",
        color: "#eceff1",
        locked: false,
        hsv: { h: 200, s: 3, v: 95 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-2",
        label: "100",
        color: "#cfd8dc",
        locked: false,
        hsv: { h: 199, s: 6, v: 86 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-3",
        label: "200",
        color: "#b0bec5",
        locked: false,
        hsv: { h: 200, s: 11, v: 77 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-4",
        label: "300",
        color: "#90a4ae",
        locked: false,
        hsv: { h: 199, s: 18, v: 68 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-5",
        label: "400",
        color: "#78909c",
        locked: false,
        hsv: { h: 199, s: 23, v: 61 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-6",
        label: "500",
        color: "#607d8b",
        locked: true,
        hsv: { h: 199, s: 31, v: 55 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-7",
        label: "600",
        color: "#546e7a",
        locked: false,
        hsv: { h: 199, s: 31, v: 48 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-8",
        label: "700",
        color: "#455a64",
        locked: false,
        hsv: { h: 200, s: 31, v: 39 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-9",
        label: "800",
        color: "#37474f",
        locked: false,
        hsv: { h: 200, s: 31, v: 31 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
      {
        id: "shade-10",
        label: "900",
        color: "#263238",
        locked: false,
        hsv: { h: 200, s: 32, v: 22 },
        selectedForH: true,
        selectedForS: true,
        selectedForV: true,
      },
    ],
  },
];
